### ISSUE TITLE
Does not support emojis

### ISSUE THREAD

**Issue by lukebatchelor** [jpnelson/bigtyper#1]
http://bigtyper.com/?txt=%F0%9F%98%80%F0%9F%98%80

Should display two '😀' faces

**Comment by ianrtracey** [comment]
+1

**Comment by jpnelson** [comment]
Hi @lukebatchelor I think this is fixed in the latest version of Chrome. Thanks for waiting, we got this fix out for you

**Comment by jpnelson** [comment]
Going to close this issue as it works now, thanks @lukebatchelor
